export const postsActionsTypes = {
  REQUEST_POSTS_START: "REQUEST_POSTS_START",
  REQUEST_POSTS_SUCCESS: "REQUEST_POSTS_SUCCESS",
  REQUEST_POSTS_FAILURE: "REQUEST_POSTS_FAILURE",
  FETCH_POSTS: "FETCH_POSTS",
};
